(function(){const q=(p,o,a,n)=>({topic:'English',prompt:p,options:o,answer:a,note:n,points:5});const add=(n,rows)=>OTHER_TESTS.push({subject:'Иностранный язык',title:'Английский язык · Вариант '+n,subtitle:'20 заданий: грамматика, лексика, перевод и понимание текста.',questions:rows.map(r=>q(...r))});
add(1,[
['He speaks as if he ___ everything.',['knows','knew','had known','is knowing'],1,'После as if для нереальной ситуации употребляется Past Simple.'],
['___ he still talking on the phone?',['Can’t','Can','May','Must'],0,'Can’t he… выражает удивление или раздражение.'],
['The castle was built in the 12th century, and the church is equally ___.',['ancient','antique','elderly','old-fashioned'],0,'Ancient означает очень древний.'],
['The firefighters ___ extinguish the fire.',['could','were able to','must','had to'],1,'Для успешно выполненного разового действия — were able to.'],
['He ___ for five minutes before he left.',['smoked','was smoking','had been smoking','has smoked'],2,'Длительное действие до другого прошлого момента — Past Perfect Continuous.'],
['They promised that they ___ us as soon as a decision was made.',['would inform','will inform','informed','inform'],0,'Future in the Past: would inform.'],
['___ Christmas Day everyone was happy.',['There is','It is','That was','It was'],3,'Для обозначения времени/даты используется формальное it.'],
['New York is one of ___ cities in the world.',['busy','busier','the busiest','the most busy'],2,'После one of требуется превосходная степень.'],
['Some holidays are cheap and ___ are expensive.',['another','others','the other holiday','other'],1,'Others заменяет существительное во множественном числе.'],
['He hardly has a nap every day, ___?',['hasn’t he','has he','doesn’t he','does he'],3,'Hardly имеет отрицательное значение, поэтому хвост положительный: does he.'],
['While I ___, someone stole my clothes.',['swam','was swimming','had swum','would swim'],1,'Фоновое длительное действие — Past Continuous.'],
['There is a man on the phone. ___ your husband.',['It is','This is','There is','It is being'],0,'При идентификации человека употребляется it is.'],
['My friend arrived ___ than I expected.',['earlier','more early','early','little early'],0,'Сравнительная степень early — earlier.'],
['John came to see me ___ Friday.',['another','the other','other','the another'],1,'The other Friday — в прошлую/другую конкретную пятницу.'],
['That voice sounds ___. I’m sure I know her.',['known','familiar','usual','low'],1,'A familiar voice — знакомый голос.'],
['Переведите: «Если бы я знал, я бы помог».',['If I know, I will help.','If I knew, I would help.','If I had known, I help.','If I knew, I helped.'],1,'Нереальное настоящее: If + Past, would + infinitive.'],
['Переведите: «Она уже закончила работу».',['She already finishes.','She has already finished the work.','She had finish work.','She is finishing yesterday.'],1,'Результат к настоящему — Present Perfect.'],
['Read: “Tom missed the bus, so he walked to work.” Why did Tom walk?',['He liked walking.','He missed the bus.','The bus was early.','He worked at home.'],1,'Причина прямо указана в тексте.'],
['Read: “The shop closes at six, but today it will stay open until eight.” When will it close today?',['At six','At seven','At eight','At nine'],2,'Today the shop stays open until eight.'],
['Choose the correct collocation.',['make a decision','do a decision','take a homework','make a photo'],0,'Нормативное сочетание — make a decision.']
]);
add(2,[
['If it ___ tomorrow, we will stay home.',['rains','will rain','rained','would rain'],0,'После if в реальном условии используется Present Simple.'],
['I wish I ___ more free time.',['have','had','will have','am having'],1,'После I wish о настоящем — Past Simple.'],
['The letter ___ yesterday.',['sent','was sent','is sent','has send'],1,'Past Simple Passive: was sent.'],
['She asked me where I ___.',['live','lived','will live','am living'],1,'В косвенном вопросе после прошедшего глагола — lived.'],
['By next June he ___ here for ten years.',['works','will work','will have worked','has worked'],2,'Результат к будущему моменту — Future Perfect.'],
['Neither Ann nor her friends ___ ready.',['is','are','was','be'],1,'Согласование с ближайшим подлежащим friends.'],
['This book is ___ than that one.',['interesting','more interesting','most interesting','the more interesting'],1,'Многосложное прилагательное образует степень с more.'],
['There isn’t ___ milk left.',['many','much','few','a few'],1,'Milk — неисчисляемое существительное.'],
['You ___ smoke here. It is prohibited.',['needn’t','mustn’t','couldn’t','wouldn’t'],1,'Mustn’t выражает запрет.'],
['I look forward to ___ from you.',['hear','hearing','heard','have heard'],1,'После to в look forward to употребляется герундий.'],
['He is responsible ___ the project.',['of','for','with','at'],1,'Устойчивое управление: responsible for.'],
['The news ___ surprising.',['were','are','was','have'],2,'News грамматически единственное число.'],
['She speaks English ___.',['fluent','fluently','more fluent','fluency'],1,'Глагол характеризует наречие fluently.'],
['Hardly ___ home when it started raining.',['I reached','had I reached','I had reached','did I reach'],1,'После hardly в начале — инверсия Past Perfect.'],
['The man ___ lives next door is a doctor.',['which','whose','who','where'],2,'Для лица-подлежащего используется who.'],
['Переведите: «Мне пришлось отказаться от билета».',['I had to refuse the ticket.','I had to turn down the ticket.','I must denied a ticket.','I was refuse ticket.'],1,'Turn down означает отказаться от предложения.'],
['Переведите: «Он занимается этой работой два года».',['He does it two years.','He has been doing this work for two years.','He did it since two years.','He is doing it yesterday.'],1,'Длительность до настоящего — Present Perfect Continuous.'],
['Read: “Anna studies every evening because her exam is next week.” Why does she study?',['She enjoys nights.','Her exam is next week.','She has no books.','Her friend asked her.'],1,'Причина указана после because.'],
['Read: “The museum is free on Sundays.” When is admission free?',['On Mondays','Every day','On Sundays','At night'],2,'Free admission is on Sundays.'],
['Choose the synonym of “rapid”.',['slow','quick','quiet','weak'],1,'Rapid и quick означают быстрый.']
]);
add(3,[
['When I arrived, they ___ dinner.',['had','were having','have','are having'],1,'Действие было в процессе — Past Continuous.'],
['The task is too difficult ___ alone.',['do','doing','to do','done'],2,'После too + adjective употребляется infinitive.'],
['He denied ___ the window.',['break','to break','breaking','broke'],2,'После deny употребляется герундий.'],
['If she had left earlier, she ___ the train.',['caught','would catch','would have caught','will catch'],2,'Third Conditional: would have + V3.'],
['The room needs ___.',['clean','to cleaning','cleaning','cleaned'],2,'Need doing имеет пассивное значение.'],
['You ___ have told me; I already knew.',['mustn’t','needn’t','couldn’t','should'],1,'Needn’t have done — действие было ненужным.'],
['It was ___ film I had ever seen.',['worse','the worst','bad','the worse'],1,'Превосходная степень: the worst.'],
['Only a ___ students passed the test.',['few','little','much','less'],0,'Students исчисляемое множественное — few.'],
['She ___ to Paris twice.',['has been','has gone','was going','had went'],0,'Has been означает побывала и вернулась.'],
['The project ___ by Friday.',['will complete','will have been completed','completed','has completing'],1,'Future Perfect Passive.'],
['He succeeded ___ solving the problem.',['at','in','on','for'],1,'Устойчивое управление: succeed in.'],
['I prefer tea ___ coffee.',['than','to','from','with'],1,'Prefer A to B.'],
['No sooner had he arrived ___ the meeting began.',['when','than','then','as'],1,'Корреляция no sooner… than.'],
['The equipment ___ very expensive.',['are','were','is','have'],2,'Equipment — неисчисляемое единственное число.'],
['This is the house ___ roof was damaged.',['who','which','whose','where'],2,'Whose выражает принадлежность.'],
['Переведите: «Жаль, что ты не смог прийти».',['It is a pity you could not come.','It is pity you cannot came.','I pity that you not come.','It was pity to not came.'],0,'Нормативная конструкция: It is a pity…'],
['Переведите: «Когда он ответил, все вздохнули с облегчением».',['When he answered, everyone sighed with relief.','When he answer, all breath easy.','After he answering, everyone sigh.','When answered he, everyone relieved.'],0,'Past Simple и устойчивое sigh with relief.'],
['Read: “Lucy took an umbrella because the sky was dark.” What did she expect?',['Strong sunshine','Rain','Snow in summer','A taxi'],1,'Dark sky and umbrella imply rain.'],
['Read: “The train was delayed by thirty minutes.” What happened?',['It arrived early.','It was cancelled.','It was half an hour late.','It changed direction.'],2,'Thirty-minute delay means half an hour late.'],
['Choose the antonym of “increase”.',['grow','reduce','raise','expand'],1,'Reduce означает уменьшать.']
]);})();

